import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import '../../models/models.dart';
import 'firing_solution_card.dart';

/// Export formats for firing solutions
class SolutionExporter {
  /// Standard military format
  static String toMilitaryFormat(FiringSolution solution) {
    return '''FIRING SOLUTION
MORTAR: ${solution.mortarType}
AZIMUTH: ${solution.azimuthDisplay}
ELEVATION: ${solution.elevationDisplay}
CHARGE: ${solution.charge}
DISTANCE: ${solution.distanceDisplay}
TOF: ${solution.timeOfFlightDisplay}
${solution.heightAdjusted ? 'HEIGHT ADJ: ${solution.heightDifference > 0 ? '+' : ''}${solution.heightDifference.toStringAsFixed(0)}m' : ''}
${solution.correction ?? ''}'''.trim();
  }
  
  /// Compact format for quick copy
  static String toCompactFormat(FiringSolution solution) {
    return 'AZ:${solution.azimuthDisplay} EL:${solution.elevationDisplay} CH:${solution.charge}';
  }
  
  /// Arma script format (for mission makers)
  static String toArmaScript(FiringSolution solution, Position mortar, Position target) {
    return '''// Mortar Fire Mission Script
// Generated by Mortar Calculator

_mortar = [${mortar.x.toStringAsFixed(2)}, ${mortar.y.toStringAsFixed(2)}, ${mortar.altitude.toStringAsFixed(1)}];
_target = [${target.x.toStringAsFixed(2)}, ${target.y.toStringAsFixed(2)}, ${target.altitude.toStringAsFixed(1)}];

// Firing Solution
_azimuth = ${solution.azimuth.toStringAsFixed(2)}; // mils
_elevation = ${solution.elevation.toStringAsFixed(2)}; // mils
_charge = ${solution.charge};

// Fire
[_mortar, _target, _azimuth, _elevation, _charge] call BIS_fnc_fireMortar;'''.trim();
  }
  
  /// Discord/TeamSpeak format
  static String toChatFormat(FiringSolution solution) {
    return '''FIRE: ${solution.mortarType} | AZ ${solution.azimuthDisplay} | EL ${solution.elevationDisplay} | CH ${solution.charge} | DST ${solution.distanceDisplay}'''.trim();
  }
  
  /// CSV format for logging
  static String toCsv(FiringSolution solution, Position mortar, Position target) {
    return '${solution.mortarType},${solution.azimuthDisplay},${solution.elevationDisplay},${solution.charge},${solution.distance.toStringAsFixed(0)},${solution.timeOfFlight.toStringAsFixed(1)},${mortar.x.toStringAsFixed(0)},${mortar.y.toStringAsFixed(0)},${target.x.toStringAsFixed(0)},${target.y.toStringAsFixed(0)}';
  }
  
  /// JSON format for API/data exchange
  static String toJson(FiringSolution solution, Position mortar, Position target) {
    return '''{
  "mortar": "${solution.mortarType}",
  "azimuth": ${solution.azimuth.toStringAsFixed(2)},
  "elevation": ${solution.elevation.toStringAsFixed(2)},
  "charge": ${solution.charge},
  "distance": ${solution.distance.toStringAsFixed(2)},
  "timeOfFlight": ${solution.timeOfFlight.toStringAsFixed(2)},
  "mortarPosition": {
    "x": ${mortar.x.toStringAsFixed(2)},
    "y": ${mortar.y.toStringAsFixed(2)},
    "altitude": ${mortar.altitude.toStringAsFixed(2)}
  },
  "targetPosition": {
    "x": ${target.x.toStringAsFixed(2)},
    "y": ${target.y.toStringAsFixed(2)},
    "altitude": ${target.altitude.toStringAsFixed(2)}
  }
}'''.trim();
  }
  
  /// Get all available formats
  static Map<ExportFormat, String Function(FiringSolution, Position, Position)> getAllFormats() {
    return {
      ExportFormat.military: (s, m, t) => toMilitaryFormat(s),
      ExportFormat.compact: (s, m, t) => toCompactFormat(s),
      ExportFormat.armaScript: (s, m, t) => toArmaScript(s, m, t),
      ExportFormat.chat: (s, m, t) => toChatFormat(s),
      ExportFormat.csv: (s, m, t) => toCsv(s, m, t),
      ExportFormat.json: (s, m, t) => toJson(s, m, t),
    };
  }
}

enum ExportFormat {
  military,
  compact,
  armaScript,
  chat,
  csv,
  json,
}

extension ExportFormatExtension on ExportFormat {
  String get displayName {
    switch (this) {
      case ExportFormat.military:
        return 'Military Format';
      case ExportFormat.compact:
        return 'Compact';
      case ExportFormat.armaScript:
        return 'Arma Script';
      case ExportFormat.chat:
        return 'Chat/Discord';
      case ExportFormat.csv:
        return 'CSV Log';
      case ExportFormat.json:
        return 'JSON';
    }
  }
  
  String get icon {
    switch (this) {
      case ExportFormat.military:
        return '📋';
      case ExportFormat.compact:
        return '📝';
      case ExportFormat.armaScript:
        return '📜';
      case ExportFormat.chat:
        return '💬';
      case ExportFormat.csv:
        return '📊';
      case ExportFormat.json:
        return '{ }';
    }
  }
}

/// Export dialog widget
class ExportSolutionDialog extends StatelessWidget {
  final FiringSolution solution;
  final Position mortar;
  final Position target;

  const ExportSolutionDialog({
    super.key,
    required this.solution,
    required this.mortar,
    required this.target,
  });

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    
    return AlertDialog(
      title: const Text('EXPORT FIRING SOLUTION'),
      content: SizedBox(
        width: double.maxFinite,
        child: ListView.builder(
          shrinkWrap: true,
          itemCount: ExportFormat.values.length,
          itemBuilder: (context, index) {
            final format = ExportFormat.values[index];
            return ListTile(
              leading: Text(format.icon),
              title: Text(format.displayName),
              subtitle: Text(
                _getPreview(format),
                maxLines: 2,
                overflow: TextOverflow.ellipsis,
                style: theme.textTheme.bodySmall,
              ),
              onTap: () => _copyAndDismiss(context, format),
            );
          },
        ),
      ),
      actions: [
        TextButton(
          onPressed: () => Navigator.pop(context),
          child: const Text('CANCEL'),
        ),
      ],
    );
  }
  
  String _getPreview(ExportFormat format) {
    final exporter = SolutionExporter.getAllFormats()[format]!;
    final text = exporter(solution, mortar, target);
    return text.split('\n').first;
  }
  
  void _copyAndDismiss(BuildContext context, ExportFormat format) async {
    final exporter = SolutionExporter.getAllFormats()[format]!;
    final text = exporter(solution, mortar, target);
    
    await Clipboard.setData(ClipboardData(text: text));
    
    if (context.mounted) {
      Navigator.pop(context);
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Copied ${format.displayName} to clipboard'),
          duration: const Duration(seconds: 2),
        ),
      );
    }
  }
}
